import { Montserrat, Ubuntu } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// Import Montserrat & Ubuntu with custom weights
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--font-ubuntu",
  weight: ["300", "400", "500", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${montserrat.variable} ${ubuntu.variable}`}>
      <ReduxProvider>
        <body className="">
          {children}
          <Toaster
            position="top-center"
            toastOptions={{
              style: {
                fontSize: "12px",
                borderRadius: "10px",
                background: "#333",
                color: "#fff",
              },
            }}
          />
        </body>
      </ReduxProvider>
    </html>
  );
}
